spring:
  datasource:
    url: jdbc:h2:mem:course
    username: sa
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
